id: PA5EC644A
initial_creation_type: input
source_metadata:
  title: Rendawa Series
  language: bo
  description: 'Texts by and about Rendawa Shönnu Lodrö (red mda'' ba gzhon nu blo
    gros, 1349–1412), the famed Sakya scholar and teacher of Tsongkhapa Lobzang Drakpa:'
  volume:
    675ffe65ffcb415e882745705840bc02:
      title: Prayer to Rendawa Shönnu Lodrö
      parent: Prayers
created_at: '2022-03-01T01:20:30.874871'
last_modified_at: '2022-03-01T01:20:30.874874'
statistics:
  total_words: 57
  total_non_words: 3
quality:
  non_words_ratio: 0.05
